{{- if and .Values.persistence.enabled (not .Values.persistence.modulesCache.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-modules-cache" (include "tiki.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "tiki.labels" . | nindent 4 }}
  {{- with .Values.persistence.modulesCache.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- if not (empty .Values.persistence.modulesCache.accessModes) }}
  {{- range .Values.persistence.modulesCache.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.persistence.modulesCache.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.modulesCache.size | quote }}
  {{- if .Values.persistence.modulesCache.storageClass }}
  storageClass: {{- .Values.persistence.modulesCache.storageClass }}
  {{- end -}}
  {{- if .Values.persistence.modulesCache.selector }}
  selector: {{- .Values.persistence.modulesCache.selector | nindent 4 }}
  {{- end -}}
  {{- if .Values.persistence.modulesCache.dataSource }}
  dataSource: {{- .Values.persistence.modulesCache.dataSource | nindent 4 }}
  {{- end }}
{{- end }}
